services:
  - type: web
    name: indiamart-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      playwright install chromium && chmod +x cloudflared && uvicorn Final_indiamart_bot:app --host 0.0.0.0 --port 8000
